(function () {
    const transcriptCache = new Map();
    let cachedVideoId = null;

    function isYouTubeWatchPage(url) {
        return /https?:\/\/(www\.)?youtube\.com\/(watch|live)/i.test(url || "");
    }

    function getCurrentVideoId(url) {
        const value = String(url || location.href || "");
        const watchMatch = value.match(/[?&]v=([^&]+)/);
        if (watchMatch) {
            return watchMatch[1];
        }
        const liveMatch = value.match(/\/live\/([^/?#&]+)/);
        return liveMatch ? liveMatch[1] : "";
    }

    function syncVideoCache() {
        const videoId = getCurrentVideoId(location.href);
        if (videoId && cachedVideoId && cachedVideoId !== videoId) {
            transcriptCache.clear();
        }
        cachedVideoId = videoId || cachedVideoId;
        return videoId;
    }

    function getYouTubePlayerResponse() {
        return globalThis.ytInitialPlayerResponse || SummarizerExtractorCore.findScriptJsonObject([
            "var ytInitialPlayerResponse = ",
            "ytInitialPlayerResponse = ",
            "window[\"ytInitialPlayerResponse\"] = "
        ]);
    }

    function getYouTubeInitialData() {
        return globalThis.ytInitialData || SummarizerExtractorCore.findScriptJsonObject([
            "var ytInitialData = ",
            "ytInitialData = ",
            "window[\"ytInitialData\"] = "
        ]);
    }

    function formatDuration(totalSeconds) {
        const seconds = Number(totalSeconds || 0);
        if (!Number.isFinite(seconds) || seconds <= 0) {
            return "";
        }
        return SummarizerExtractorCore.formatTimestamp(seconds);
    }

    function formatViewCount(rawCount) {
        const parsed = Number(String(rawCount || "").replace(/[^\d]/g, ""));
        if (!Number.isFinite(parsed) || parsed <= 0) {
            return "";
        }
        return new Intl.NumberFormat().format(parsed) + " views";
    }

    function selectBestThumbnail(thumbnails) {
        const items = Array.isArray(thumbnails) ? thumbnails : [];
        if (!items.length) {
            return "";
        }
        return items
            .slice()
            .sort((left, right) => {
                const leftArea = Number(left.width || 0) * Number(left.height || 0);
                const rightArea = Number(right.width || 0) * Number(right.height || 0);
                return rightArea - leftArea;
            })[0].url || "";
    }

    function getPreferredCaptionLanguage() {
        const rawLanguage = document.documentElement.lang || navigator.language || "en";
        return String(rawLanguage).toLowerCase().split("-")[0];
    }

    function scoreCaptionTrack(track, preferredLang) {
        const languageCode = String(track.languageCode || "").toLowerCase();
        const trackName = SummarizerExtractorCore.getTextFromRuns(track.name).toLowerCase();
        const vssId = String(track.vssId || "").toLowerCase();
        const isAutoGenerated =
            String(track.kind || "").toLowerCase() === "asr" ||
            trackName.includes("auto-generated") ||
            /^a\./.test(vssId);

        let score = 0;
        if (!isAutoGenerated && languageCode === preferredLang) score += 100;
        if (!isAutoGenerated && languageCode.startsWith(preferredLang + "-")) score += 90;
        if (!isAutoGenerated && languageCode === "en") score += 80;
        if (isAutoGenerated && languageCode === preferredLang) score += 70;
        if (isAutoGenerated && languageCode === "en") score += 60;
        if (!isAutoGenerated) score += 20;
        return score;
    }

    function rankCaptionTracks(captionTracks) {
        const preferredLang = getPreferredCaptionLanguage();
        return (Array.isArray(captionTracks) ? captionTracks.slice() : []).sort((left, right) => {
            return scoreCaptionTrack(right, preferredLang) - scoreCaptionTrack(left, preferredLang);
        });
    }

    function buildCaptionRequestUrl(baseUrl, format) {
        const url = new URL(SummarizerExtractorCore.decodeYouTubeUrl(baseUrl));
        if (format) {
            url.searchParams.set("fmt", format);
        }
        return url.toString();
    }

    function normalizeTranscriptSegments(items) {
        return (items || [])
            .map((item) => {
                const text = SummarizerCleaners.cleanText(item.text || "");
                const startSeconds = Math.max(0, Number(item.startSeconds || 0));
                if (!text) {
                    return null;
                }
                return {
                    text,
                    startSeconds,
                    startLabel: SummarizerExtractorCore.formatTimestamp(startSeconds)
                };
            })
            .filter(Boolean);
    }

    async function fetchTranscriptSegmentsJson(baseUrl) {
        const response = await fetch(buildCaptionRequestUrl(baseUrl, "json3"));
        if (!response.ok) {
            throw new Error("Transcript request failed.");
        }

        const rawText = await response.text();
        const payloadText = String(rawText || "").trim();
        if (!payloadText) {
            return [];
        }

        let payload;
        try {
            payload = JSON.parse(payloadText);
        } catch (error) {
            throw new Error("Transcript JSON payload was empty or invalid.");
        }

        const events = Array.isArray(payload && payload.events) ? payload.events : [];
        return normalizeTranscriptSegments(
            events
                .map((event) => {
                    const segs = Array.isArray(event.segs) ? event.segs : [];
                    return {
                        text: segs
                            .map((segment) => SummarizerCleaners.decodeHtmlEntities(segment.utf8 || ""))
                            .join(""),
                        startSeconds: Number(event.tStartMs || 0) / 1000
                    };
                })
                .filter((item) => SummarizerCleaners.cleanText(item.text).length > 0)
        );
    }

    async function fetchTranscriptSegmentsXml(baseUrl) {
        const response = await fetch(buildCaptionRequestUrl(baseUrl, ""));
        if (!response.ok) {
            throw new Error("Transcript request failed.");
        }

        const xmlText = await response.text();
        const xml = new DOMParser().parseFromString(xmlText, "text/xml");
        const textNodes = Array.from(xml.getElementsByTagName("text"));
        return normalizeTranscriptSegments(
            textNodes.map((node) => ({
                text: SummarizerCleaners.decodeHtmlEntities(node.textContent || ""),
                startSeconds: Number(node.getAttribute("start") || 0)
            }))
        );
    }

    async function fetchTranscriptSegments(baseUrl) {
        try {
            const jsonSegments = await fetchTranscriptSegmentsJson(baseUrl);
            if (jsonSegments.length) {
                return jsonSegments;
            }
        } catch (error) {
            if (!/empty or invalid/i.test(String(error && error.message || ""))) {
                console.log("YouTube JSON transcript fetch failed, retrying with XML:", error);
            }
        }
        return fetchTranscriptSegmentsXml(baseUrl);
    }

    async function waitForElement(selector, timeoutMs) {
        const timeout = Number(timeoutMs || 0) || 5000;
        const startTime = Date.now();

        while (Date.now() - startTime < timeout) {
            const element = document.querySelector(selector);
            if (element) {
                return element;
            }
            // Check for transcript segments appearing anywhere as an alternative success condition
            if (document.querySelectorAll('ytd-transcript-segment-renderer, .segment-renderer').length > 0) {
                return true;
            }
            await new Promise((resolve) => setTimeout(resolve, 200));
        }

        return null;
    }

    async function fetchTranscriptFromDom() {
        // 1. First check if transcript panel is already open and extract from it
        const existingSegments = extractTranscriptFromOpenPanel();
        if (existingSegments.length > 0) {
            return existingSegments;
        }

        // 2. Try to find and click transcript button (localized)
        const transcriptButton = await findTranscriptButton();
        if (!transcriptButton) {
            return [];
        }

        transcriptButton.click();
        await waitForElement(
            'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"], ' +
            'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript-panel"]',
            5000
        );
        await new Promise((resolve) => setTimeout(resolve, 500));

        // 3. Extract from the newly opened panel
        return extractTranscriptFromOpenPanel();
    }

    function findTranscriptButton() {
        // Check expand button first
        const expandButton = document.querySelector("#expand");
        if (expandButton && expandButton.offsetParent !== null) {
            expandButton.click();
            // Small delay to let description expand
            return new Promise(resolve => setTimeout(() => {
                const btn = findTranscriptButtonAfterExpand();
                resolve(btn);
            }, 500));
        }
        return findTranscriptButtonAfterExpand();
    }

    function findTranscriptButtonAfterExpand() {
        const buttonSelectors = [
            'ytd-video-description-transcript-section-renderer button',
            'button[aria-label*="transcript" i]',
            'button[aria-label*="bản chép" i]',
            'button[aria-label*="Bản chép" i]'
        ];

        for (const selector of buttonSelectors) {
            const btn = document.querySelector(selector);
            if (btn) {
                return btn;
            }
        }

        return Array.from(document.querySelectorAll("button")).find((button) => {
            const text = String(button.textContent || "").toLowerCase();
            const ariaLabel = String(button.getAttribute("aria-label") || "").toLowerCase();
            return text.includes("transcript") ||
                   text.includes("bản chép") ||
                   ariaLabel.includes("transcript") ||
                   ariaLabel.includes("bản chép");
        }) || null;
    }

    function parseTimestamp(label) {
        if (!label) return null;
        // Match timestamps like 1:23, 01:23, 1:23:45, [1:23]
        const match = label.match(/(?:\b|\[)?(?:\d{1,2}:)?\d{1,2}:\d{2}(?:\b|\])?/);
        if (!match) return null;
        
        const clean = match[0].replace(/[\[\]]/g, '');
        const parts = clean.trim().split(":").map((value) => Number(value));
        
        let startSeconds = 0;
        if (parts.length === 3 && parts.every(Number.isFinite)) {
            startSeconds = parts[0] * 3600 + parts[1] * 60 + parts[2];
        } else if (parts.length === 2 && parts.every(Number.isFinite)) {
            startSeconds = parts[0] * 60 + parts[1];
        } else {
            return null;
        }
        return startSeconds;
    }

    function deepQuerySelectorAll(selector, root = document) {
        const results = [];
        const query = (element) => {
            if (!element) return;
            if (element.matches && element.matches(selector)) {
                results.push(element);
            }
            if (element.shadowRoot) {
                query(element.shadowRoot);
            }
            Array.from(element.children).forEach(query);
        };
        query(root);
        // Also just try document query as baseline
        const docs = Array.from(document.querySelectorAll(selector));
        return Array.from(new Set([...results, ...docs]));
    }

    function extractTranscriptFromOpenPanel() {
        let segments = [];

        // 1. Try known element selectors
        const knownSelectors = [
            'ytd-transcript-segment-renderer',
            '.segment-renderer',
            '[segment-renderer]'
        ];
        
        for (const sel of knownSelectors) {
            const nodes = deepQuerySelectorAll(sel);
            if (nodes.length > 0) {
                Array.from(nodes).forEach(node => {
                    const tsMatch = node.textContent.match(/(?:\b|\[)?(?:\d{1,2}:)?\d{1,2}:\d{2}(?:\b|\])?/);
                    let tsStr = tsMatch ? tsMatch[0] : (node.getAttribute("aria-label") || "");
                    const startSeconds = parseTimestamp(tsStr);
                    
                    if (startSeconds !== null) {
                        let textNode = node.querySelector('yt-formatted-string, .segment-text, .text');
                        let text = textNode ? textNode.textContent : node.textContent;
                        text = text.replace(tsStr, '').trim();
                        
                        segments.push({
                            text: SummarizerCleaners.cleanText(text),
                            startSeconds
                        });
                    }
                });
                if (segments.length > 0) break;
            }
        }

        // 2. Generic row scan inside engagement panels
        if (segments.length === 0) {
            const panels = deepQuerySelectorAll('ytd-engagement-panel-section-list-renderer, ytd-transcript-search-panel-renderer, #panels');
            panels.forEach(panel => {
                // Find anything that looks like a row with a timestamp
                const rows = panel.querySelectorAll ? Array.from(panel.querySelectorAll('div, ytd-transcript-segment-renderer')) : deepQuerySelectorAll('div, ytd-transcript-segment-renderer', panel);
                rows.forEach(row => {
                    // Check if row has direct text content matching a timestamp
                    const text = row.textContent || "";
                    const tsMatch = text.match(/^\s*(?:\b|\[)?(?:\d{1,2}:)?\d{1,2}:\d{2}(?:\b|\])?\s*/);
                    if (tsMatch && text.length > tsMatch[0].length && text.length < 500) {
                        const startSeconds = parseTimestamp(tsMatch[0]);
                        if (startSeconds !== null) {
                            segments.push({
                                text: SummarizerCleaners.cleanText(text.substring(tsMatch[0].length)),
                                startSeconds
                            });
                        }
                    }
                });
            });
        }

        // 3. Deduplicate
        let unique = [];
        const seen = new Set();
        segments.forEach(seg => {
            const key = seg.startSeconds + ":" + seg.text.substring(0, 20);
            if (!seen.has(key) && seg.text.length > 0) {
                seen.add(key);
                unique.push(seg);
            }
        });
        
        unique.sort((a, b) => a.startSeconds - b.startSeconds);
        
        console.log("[Summarizer] DOM Transcript extraction:", {
            foundSegments: unique.length,
            rawSegmentsBeforeDedup: segments.length
        });

        // 3. Last resort: scan ALL text nodes for timestamp + text pairs
        if (unique.length === 0) {
            const walker = document.createTreeWalker(
                document.body,
                NodeFilter.SHOW_TEXT,
                null,
                false
            );
            let textNode;
            while ((textNode = walker.nextNode()) !== null) {
                const text = textNode.textContent || "";
                // Look for lines that start with a timestamp pattern
                const lines = text.split("\n");
                for (const line of lines) {
                    const trimmed = line.trim();
                    const tsMatch = trimmed.match(/^(\s*(?:\b|\[)?(?:\d{1,2}:)?\d{1,2}:\d{2}(?:\b|\])?\s*)/);
                    if (tsMatch && trimmed.length > tsMatch[0].length && trimmed.length < 500) {
                        const startSeconds = parseTimestamp(tsMatch[0]);
                        if (startSeconds !== null) {
                            const segText = SummarizerCleaners.cleanText(trimmed.substring(tsMatch[0].length));
                            if (segText.length > 0) {
                                unique.push({ text: segText, startSeconds });
                            }
                        }
                    }
                }
            }
            // Re-dedupe
            const seen = new Set();
            unique = unique.filter(seg => {
                const key = seg.startSeconds + ":" + seg.text.substring(0, 20);
                return !seen.has(key) && (seen.add(key), true);
            });
            unique.sort((a, b) => a.startSeconds - b.startSeconds);
        }
        
        console.log("[Summarizer] DOM Transcript extraction:", {
            foundSegments: unique.length,
            rawSegmentsBeforeDedup: segments.length
        });

        return normalizeTranscriptSegments(unique);
    }

    function stripDurationLabelFromText(text) {
        // YouTube VN accessibility text often glues duration to caption: "20 giâyCu thể...".
        const value = String(text || "").trim();
        return value
            .replace(/^\d+\s*(?:phút|phut|minutes?|mins?|menit|minuut)(?:\s*,\s*|\s+and\s+|\s+)?(?:\d+\s*(?:giây|giay|seconds?|secs?|detik|seconde))?[\s,.:;\-]*/i, "")
            .replace(/^\d+\s*(?:giây|giay|seconds?|secs?|detik|seconde)[\s,.:;\-]*/i, "")
            .trim();
    }

    function buildTimestampedTranscript(segments) {
        return (segments || [])
            .map((segment) => {
                const cleaned = stripDurationLabelFromText(segment.text);
                return cleaned ? `[${segment.startLabel}] ${cleaned}` : `[${segment.startLabel}]`;
            })
            .join("\n");
    }

    function extractYouTubeChapters(initialData) {
        const markersMap =
            initialData &&
            initialData.playerOverlays &&
            initialData.playerOverlays.playerOverlayRenderer &&
            initialData.playerOverlays.playerOverlayRenderer.decoratedPlayerBarRenderer &&
            initialData.playerOverlays.playerOverlayRenderer.decoratedPlayerBarRenderer.decoratedPlayerBarRenderer &&
            initialData.playerOverlays.playerOverlayRenderer.decoratedPlayerBarRenderer.decoratedPlayerBarRenderer.playerBar &&
            initialData.playerOverlays.playerOverlayRenderer.decoratedPlayerBarRenderer.decoratedPlayerBarRenderer.playerBar.multiMarkersPlayerBarRenderer &&
            initialData.playerOverlays.playerOverlayRenderer.decoratedPlayerBarRenderer.decoratedPlayerBarRenderer.playerBar.multiMarkersPlayerBarRenderer.markersMap;

        const chapterEntry = Array.isArray(markersMap)
            ? markersMap.find((item) => item.key === "DESCRIPTION_CHAPTERS" || item.key === "AUTO_CHAPTERS")
            : null;
        const chapters = chapterEntry && chapterEntry.value && chapterEntry.value.chapters;

        return (Array.isArray(chapters) ? chapters : [])
            .map((chapter) => {
                const renderer = chapter.chapterRenderer || {};
                const title = SummarizerExtractorCore.getTextFromRuns(renderer.title);
                const startSeconds = Number(renderer.timeRangeStartMillis || 0) / 1000;
                if (!title) {
                    return null;
                }
                return {
                    title,
                    startSeconds,
                    startLabel: SummarizerExtractorCore.formatTimestamp(startSeconds)
                };
            })
            .filter(Boolean);
    }

    function extractYouTubeVideoDetails(playerResponse, initialData, selectedTrack) {
        const videoDetails = (playerResponse && playerResponse.videoDetails) || {};
        const microformat =
            playerResponse &&
            playerResponse.microformat &&
            playerResponse.microformat.playerMicroformatRenderer;
        const durationSeconds = Number(videoDetails.lengthSeconds || 0);

        return {
            channelName: videoDetails.author || (microformat && microformat.ownerChannelName) || "",
            durationText: formatDuration(durationSeconds),
            durationSeconds: durationSeconds || 0,
            publishDate: (microformat && (microformat.publishDate || microformat.uploadDate)) || "",
            viewCountText:
                SummarizerExtractorCore.getTextFromRuns(microformat && microformat.viewCount) ||
                formatViewCount(videoDetails.viewCount),
            thumbnailUrl: selectBestThumbnail(
                (videoDetails.thumbnail && videoDetails.thumbnail.thumbnails) ||
                (microformat && microformat.thumbnail && microformat.thumbnail.thumbnails) ||
                []
            ),
            description: SummarizerCleaners.cleanText(
                videoDetails.shortDescription ||
                SummarizerExtractorCore.getTextFromRuns(microformat && microformat.description) ||
                ""
            ),
            chapters: extractYouTubeChapters(initialData),
            transcriptLanguage: String((selectedTrack && selectedTrack.languageCode) || "").toLowerCase(),
            captionTrackLabel:
                SummarizerExtractorCore.getTextFromRuns(selectedTrack && selectedTrack.name) ||
                String((selectedTrack && selectedTrack.languageCode) || ""),
            hasTimestamps: true,
            transcriptFormat: "timestamped"
        };
    }

    async function extractYouTubeTranscript() {
        if (!isYouTubeWatchPage(location.href)) {
            return null;
        }

        const videoId = syncVideoCache();
        const cacheKey = videoId || location.href;
        if (transcriptCache.has(cacheKey)) {
            return transcriptCache.get(cacheKey);
        }

        const playerResponse = getYouTubePlayerResponse();
        const initialData = getYouTubeInitialData();
        const captionTracks =
            playerResponse &&
            playerResponse.captions &&
            playerResponse.captions.playerCaptionsTracklistRenderer &&
            playerResponse.captions.playerCaptionsTracklistRenderer.captionTracks;

        let transcriptSegments = [];
        let workingTrack = null;

        for (const track of rankCaptionTracks(captionTracks)) {
            if (!track || !track.baseUrl) {
                continue;
            }
            try {
                const attempt = await fetchTranscriptSegments(track.baseUrl);
                const plainAttempt = SummarizerCleaners.cleanText(
                    attempt.map((segment) => segment.text).join(" ")
                );
                if (plainAttempt.length >= 80) {
                    transcriptSegments = attempt;
                    workingTrack = track;
                    break;
                }
            } catch (error) {
                console.log("Caption track attempt failed:", track.languageCode, error);
            }
        }

        if (!transcriptSegments.length) {
            transcriptSegments = await fetchTranscriptFromDom();
        }

        if (!transcriptSegments.length) {
            throw new Error("No transcript is available for this YouTube video.");
        }

        const plainTranscript = SummarizerCleaners.cleanText(
            transcriptSegments.map((segment) => segment.text).join(" ")
        );
        if (!plainTranscript || plainTranscript.length < 80) {
            throw new Error("Transcript is too short to summarize.");
        }

        const timestampedTranscript = buildTimestampedTranscript(transcriptSegments);
        const title =
            String(
                (playerResponse && playerResponse.videoDetails && playerResponse.videoDetails.title) || ""
            ).trim() ||
            document.title.replace(/\s*-\s*YouTube\s*$/, "").trim() ||
            "YouTube video";

        const result = {
            sourceType: "youtube",
            title,
            url: location.href,
            content: timestampedTranscript,
            contentRaw: timestampedTranscript,
            contentForPrompt: timestampedTranscript,
            transcriptFull: timestampedTranscript,
            transcriptSegments,
            videoDetails: extractYouTubeVideoDetails(playerResponse, initialData, workingTrack)
        };
        transcriptCache.set(cacheKey, result);
        return result;
    }

    globalThis.SummarizerYoutubeExtractor = {
        isYouTubeWatchPage,
        extractYouTubeTranscript
    };
})();
